version: '3.8'

services:
  backend-app:
    build: ./Backend # Build the image from the Dockerfile in the Backend directory
    container_name: spring-boot-backend
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
